sudo required

services: docker

before_script:
  - docker build -t neerajbhattneeraj/client -f ./client/Dockerfile.dev ./client

script:
  - docker run neerajbhattneeraj/client npm test -- --converage

after_success:
  - docker build -t neerajbhattneeraj/complex-client ./client
  - docker build -t neerajbhattneeraj/complex-server ./server
  - docker build -t neerajbhattneeraj/complex-worker ./worker
  - docker build -t neerajbhattneeraj/complex-nginx ./nginx
